/**
* Kezdeményezés Követő
* This is a mobil client for tracking initiative in D&D and other ttrpgs.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.z80h3x.kezd_kov.data.network.models


/**
 * 
 * @param name 
 * @param desc 
 * @param options 
 * @param damage 
 * @param attack_bonus 
 * @param dc 
 */
data class Action (
    val name: String? = null,
    val desc: String? = null,
    val options: Any? = null,
    val damage: Array<Any>? = null,
    val attack_bonus: Int? = null,
    val dc: Any? = null
) {

}

